version: '3.6'
services:
  #######################################
  # Application
  #######################################
  {DOMAIN_NAME}-wordpress:
    build:
      context: .
      args:
        WP_VERSION: ${WP_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    container_name: {DOMAIN_NAME}-wordpress
    volumes:
      # WordPress wp-content folder
      - ./../wp-content/:/var/www/html/wp-content/:rw,cached
      # Configs
      - ./../wp-docker/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      # Debug log
      - ./../logs/wordpress:/var/log/wordpress
    env_file: .env
    environment:
      VIRTUAL_HOST : ${VIRTUAL_HOST}
      WORDPRESS_DB_NAME : ${MYSQL_DATABASE}
      WORDPRESS_DB_USER : root
      WORDPRESS_TABLE_PREFIX : ${TABLE_PREFIX}
      WORDPRESS_DB_HOST : ${MYSQL_HOST}
      WORDPRESS_DB_PASSWORD : ${MYSQL_ROOT_PASSWORD}
      WP_VERSION : ${WP_VERSION}
      WORDPRESS_DEBUG : ${WP_DEBUG}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ALLOW_MULTISITE', ${WP_ALLOW_MULTISITE} );
        define( 'MULTISITE', ${WP_ALLOW_MULTISITE} );
        define( 'ALTERNATE_WP_CRON', ${ALTERNATE_WP_CRON} );
        define( 'WP_DEBUG_DISPLAY', ${WP_DEBUG_DISPLAY} );
        define( 'WP_DEBUG_LOG', '/var/log/wordpress/debug.log' );
        define( 'FS_METHOD', 'direct' );
      NEXT_VAR: 0
    depends_on:
      - {DOMAIN_NAME}-mysql
    restart: always

  #######################################
  # Database
  #######################################
  {DOMAIN_NAME}-mysql:
    image: mariadb
    container_name: {DOMAIN_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE : ${MYSQL_DATABASE}
    restart: always
    ports:
      - '${PORT}:3306'
    volumes:
      - {DOMAIN_NAME}_db_data:/var/lib/mysql
    # Set max_allowed_packet to 256M (or any other value)
    command: ['--max_allowed_packet=32505856']

  #######################################
  # phpMyAdmin
  #######################################
  {DOMAIN_NAME}-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - {DOMAIN_NAME}-mysql
    links:
      - {DOMAIN_NAME}-mysql
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${PMA_VIRTUAL_HOST}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    restart: always
    volumes:
      # Configs
      - ./../wp-docker/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini

networks:
  default:
    name: dockerwp
    external: true

volumes:
  {DOMAIN_NAME}_db_data:
